version: '3'
services:

  payten-db:
    image: postgres
    container_name: payten-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: payten-user
      POSTGRES_PASSWORD: payten-password
      POSTGRES_DB: postgres
    networks:
      - paytenNetwork

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - paytenNetwork

  credit-system-api:
    build: .
    container_name: credit-system-api
    depends_on:
      - payten-db
      - redis
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payten-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=payten-user
      - SPRING_DATASOURCE_PASSWORD=payten-password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - paytenNetwork

networks:
  paytenNetwork:
    driver: "bridge"